MODEL:
  TYPE: nas
  NUM_CLASSES: 1000
  LOSS_FUN: label_smoothed_cross_entropy
  LABEL_SMOOTHING_EPS: 0.1
NAS:
  GENOTYPE: unnas_cityscapes_seg
  WIDTH: 44
  DEPTH: 14
  AUX: True
  DROP_PROB: 0.0
OPTIM:
  BASE_LR: 0.5
  LR_POLICY: cos
  MAX_EPOCH: 250
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00003
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 1024
  IM_SIZE: 224
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 1000
  IM_SIZE: 256
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
