MODEL:
  TYPE: nas_search
  NUM_CLASSES: 19
  ASPP_CHANNELS: 64
  ASPP_RATES: [6]
NAS:
  WIDTH: 16
  DEPTH: 12
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 400
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0003
  ITER_LR: False
  ARCH_BASE_LR: 0.0003
  ARCH_WEIGHT_DECAY: 0.001
TRAIN:
  DATASET: cityscapes
  SPLIT: train
  BATCH_SIZE: 32
  IM_SIZE: 321
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 1
  PORTION: 0.5
TEST:
  BATCH_SIZE: 32
  IM_SIZE: 512
TASK: seg
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
