MODEL:
  TYPE: nas
  NUM_CLASSES: 19
  ASPP_CHANNELS: 256
  ASPP_RATES: [6, 12, 18]
NAS:
  GENOTYPE: unnas_imagenet22k_col
  WIDTH: 78
  DEPTH: 12
  AUX: False
  DROP_PROB: 0.0
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 2700
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: cityscapes
  SPLIT: train
  BATCH_SIZE: 64
  IM_SIZE: 769
  CHECKPOINT_PERIOD: 100
  EVAL_PERIOD: 1
TEST:
  DATASET: cityscapes
  SPLIT: val
  BATCH_SIZE: 8
  IM_SIZE: 1024
TASK: seg
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 1
CUDNN:
  BENCHMARK: True
OUT_DIR: .
