MODEL:
  TYPE: nas
  NUM_CLASSES: 313
  INPUT_CHANNELS: 1
NAS:
  CUSTOM_GENOTYPE:
  - - [sep_conv_3x3, 0]
    - [sep_conv_5x5, 0]
    - [none, 2]
    - [dil_conv_3x3, 2]
    - [sep_conv_5x5, 3]
    - [max_pool_3x3, 2]
    - [skip_connect, 0]
    - [sep_conv_3x3, 3]
  - [2, 3, 4, 5]
  - - [skip_connect, 1]
    - [max_pool_3x3, 0]
    - [max_pool_3x3, 0]
    - [dil_conv_3x3, 1]
    - [skip_connect, 3]
    - [none, 0]
    - [dil_conv_3x3, 0]
    - [sep_conv_3x3, 0]
  - [2, 3, 4, 5]
  GENOTYPE: custom
  WIDTH: 16
  DEPTH: 20
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 32
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
TASK: col
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
OUT_DIR: .
