MODEL:
  TYPE: nas
  NUM_CLASSES: 1000
NAS:
  GENOTYPE: custom
  CUSTOM_GENOTYPE:
  - - [sep_conv_5x5, 1]
    - [dil_conv_5x5, 1]
    - [skip_connect, 0]
    - [sep_conv_5x5, 0]
    - [none, 2]
    - [skip_connect, 0]
    - [sep_conv_5x5, 3]
    - [sep_conv_3x3, 1]
  - [2, 3, 4, 5]
  - - [skip_connect, 0]
    - [sep_conv_3x3, 0]
    - [dil_conv_3x3, 0]
    - [sep_conv_5x5, 1]
    - [skip_connect, 0]
    - [dil_conv_5x5, 0]
    - [max_pool_3x3, 3]
    - [max_pool_3x3, 2]
  - [2, 3, 4, 5]
  WIDTH: 32
  DEPTH: 22
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.0125
  LR_POLICY: cos
  MAX_EPOCH: 5
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00005
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 32
  IM_SIZE: 255
  EVAL_PERIOD: 1
  GRAY_PERCENTAGE: 0.3
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 25
  IM_SIZE: 256
TASK: jig
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
