MODEL:
  TYPE: nas_search
  NUM_CLASSES: 4
NAS:
  WIDTH: 16
  DEPTH: 8
OPTIM:
  BASE_LR: 0.2
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.00003
  ITER_LR: False
  ARCH_BASE_LR: 0.0006
  ARCH_WEIGHT_DECAY: 0.001
TRAIN:
  DATASET: imagenet22k
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 1
  PORTION: 0.5
TEST:
  BATCH_SIZE: 128
  IM_SIZE: 256
TASK: rot
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
